_BASE_: "swinbase_vigor_easy_stage1.yaml"

DATASETS:
  TRAIN: ("vigor_easy_train_llmseg_noisy",)
  TEST: ()

SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (72000, 96000)
  MAX_ITER: 108000

DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [16]
  USE_RFS: [False]
  DATASET_MIN_SIZES: [[640, 800]]
  DATASET_MAX_SIZES: [1333]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ["part"]
  STRONG_AUG_ON_PARSED: False
  NUM_WORKERS: 8

VIGOR_NOISY:
  ENABLED: True
  NOISY_RATIO: 0.2
  NEARBY_TOPK: 1
  MAX_CENTER_DISTANCE: 150.0
  RANDOM_SEED: 42

OUTPUT_DIR: "output/VLPart/vigor_swinbase_easy_stage1_gt_plus_nearby_noisy_ratio20_top1_dist150"
