#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VLPART_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${VLPART_ROOT}/.." && pwd)"
cd "${VLPART_ROOT}"

# ========== Environment ==========
VENV_ROOT="${REPO_ROOT}/.venv"
PYTHON_BIN="${VENV_ROOT}/bin/python"
GPU_ID="0"

if [[ ! -x "${PYTHON_BIN}" ]]; then
  echo "Python not found or not executable: ${PYTHON_BIN}" >&2
  exit 1
fi

PY_SITE="$("${PYTHON_BIN}" -c 'import site; print(site.getsitepackages()[0])')"
export PATH="/usr/local/cuda/bin:${VENV_ROOT}/bin:${PATH}"
export LD_LIBRARY_PATH="${PY_SITE}/torch/lib:${LD_LIBRARY_PATH:-}"
export PYTHONPATH="${REPO_ROOT}/detectron2:${VLPART_ROOT}:${VLPART_ROOT}/demo:${PYTHONPATH:-}"

# ========== VLPart model ==========
CONFIG_FILE="configs/vigor/swinbase_vigor_easy_stage1.yaml"
WEIGHTS="/opt/data/private/LLMSeg/VLPart/output/VLPart/vigor_swinbase_easy_stage1_bs16_lr4e-5/model_final.pth"
CONFIDENCE_THRESHOLD="0.05"

# ========== Dataset ==========
DATA_DIR="/opt/data/private/LLMSeg/dataset/VIGOR-100K_new/test"
EASY_JSON="open_vocab_grasp_easy_object_mix.json"
HARD_JSON="open_vocab_grasp_hard_object_mix.json"
SPLIT="both"

# ========== LLMSeg Top-K object masks ==========
LLMSEG_TOPK_MASKS_DIR="/opt/data/private/LLMSeg/vis_output_object_topk_testset/topk_masks"
TOPK_MASK_K="3"

# ========== Vocabulary ==========
VOCABULARY="custom"
CUSTOM_VOCABULARY="cylindrical side surface,hexagonal side face,flat side surface,whole object"

# ========== Output / cache ==========
OUTPUT_ROOT="vlpart_vigor_outputs/llmseg_topk_formula_alpha_sweep_k${TOPK_MASK_K}"
OUTPUT_DIR="${OUTPUT_ROOT}/results"
# This path is required by the shared parser but is not read in sweep mode.
CHECKPOINT_PATH="${OUTPUT_ROOT}/checkpoints/unused_formula_alpha_sweep.pt"
# Reuse numeric test feature cache generated by the reranker/formula scorer pipeline.
FEATURE_CACHE_DIR="vlpart_vigor_outputs/llmseg_topk_reranker_k${TOPK_MASK_K}/candidate_feature_cache_test"

# ========== Alpha sweep ==========
ALPHA_START="0.0"
ALPHA_END="1.0"
ALPHA_STEP="0.1"
RANKING_TEMPERATURE="1.0"

# ========== Evaluation ==========
SSR_THRESHOLD="0.5"
MAX_SAMPLES=""
PREDICTION_CACHE_SIZE="128"
SKIP_ICR="true"
DEBUG="0"

echo "========================================================================"
echo "  Test VLPart top-K formula scorer alpha sweep"
echo "========================================================================"
echo "Formula: (alpha * pred_similarity + (1 - alpha) * pred_iou) * vlpart_score"
echo "Alpha sweep: ${ALPHA_START}..${ALPHA_END} step ${ALPHA_STEP}"
echo "Ranking temperature: ${RANKING_TEMPERATURE}"
echo "Top-K masks: ${LLMSEG_TOPK_MASKS_DIR}"
echo "Top-K K: ${TOPK_MASK_K}"
echo "Output dir: ${OUTPUT_DIR}"
echo "Feature cache: ${FEATURE_CACHE_DIR}"
echo "Skip ICR: ${SKIP_ICR}"
echo "========================================================================"

ARGS=(
  --mode test_formula_alpha_sweep
  --config-file "${CONFIG_FILE}"
  --weights "${WEIGHTS}"
  --data_dir "${DATA_DIR}"
  --easy_json_file "${EASY_JSON}"
  --hard_json_file "${HARD_JSON}"
  --split "${SPLIT}"
  --llmseg_topk_masks_dir "${LLMSEG_TOPK_MASKS_DIR}"
  --topk_mask_k "${TOPK_MASK_K}"
  --checkpoint_path "${CHECKPOINT_PATH}"
  --output_dir "${OUTPUT_DIR}"
  --vocabulary "${VOCABULARY}"
  --custom_vocabulary "${CUSTOM_VOCABULARY}"
  --confidence-threshold "${CONFIDENCE_THRESHOLD}"
  --ssr_threshold "${SSR_THRESHOLD}"
  --device "cuda:${GPU_ID}"
  --prediction_cache_size "${PREDICTION_CACHE_SIZE}"
  --candidate_feature_cache_dir "${FEATURE_CACHE_DIR}"
  --formula_alpha_start "${ALPHA_START}"
  --formula_alpha_end "${ALPHA_END}"
  --formula_alpha_step "${ALPHA_STEP}"
  --ranking_temperature "${RANKING_TEMPERATURE}"
)

if [[ "${SKIP_ICR}" == "true" || "${SKIP_ICR}" == "1" ]]; then
  ARGS+=(--skip_icr)
fi

if [[ -n "${MAX_SAMPLES}" ]]; then
  ARGS+=(--max_samples "${MAX_SAMPLES}")
fi

if [[ "${DEBUG}" == "true" || "${DEBUG}" == "1" ]]; then
  ARGS+=(--debug)
fi

"${PYTHON_BIN}" tools/vigor_vlpart_topk_reranker.py "${ARGS[@]}"

echo ""
echo "========================================================================"
echo "  VLPart top-K formula alpha sweep finished"
echo "========================================================================"
